"""Hand-read crude-direction labels for the 01-04 Sep 2026 window (ids 1426-2443).

Same convention and same purpose as `tests.direction_labels`, which covers the
earlier 751-1124 window. Kept as a separate module because that one is what the
v2 stance lexicon was tuned against: this set was labelled after the fact and
never fed back into the lexicon, so it is the held-out number.

The window is dominated by one running story -- US strikes on Iran, Iranian
retaliation across the Gulf, and Hormuz traffic falling to roughly a third of
its 10-day average. That makes it a harder and more useful test than the
earlier set: the same entities appear on both sides of the trade all week, so a
scorer cannot do well here by keying on "Iran" alone.

    +1  bullish -- supply threatened, coercion against a producer, chokepoint
                   disruption, demand added
    -1  bearish -- de-escalation, sanctions relief, supply or a deal that adds
                   barrels, reassurance that a feared disruption did not happen
     0  no crude signal -- casualty counts, diplomatic and cultural retaliation,
                   central-bank commentary about oil, settlement levels quoted
                   without a move, domestic retail fuel politics, non-energy news

Where a call was genuinely arguable it is labelled 0 rather than forced to a
side, so the directional subset here is the part a trader would not dispute.
"""

BULLISH, BEARISH, NOSIGNAL = 1, -1, 0

#: (headline id, title, true direction for crude)
LABELLED: list[tuple[int, str, int]] = [
    (1426, "US Treasury Secretary Bessent: 85%-90% of Iran factories have the ability to rebuild.", NOSIGNAL),
    (1427, "US Treasury Secretary Bessent: Iran probably has world's 3rd-greatest energy resource.", NOSIGNAL),
    (1428, "US Treasury Secretary Bessent on Iran sanctions: Sanctions plus blockade on Iran will work. We are probably going to announce bank sanction this week and next week.", BULLISH),
    (1429, "US Treasury Secretary Bessent on Iran Sanctions: We have great support from the EU, ECB, UK, UAE, and Bahrain.", BULLISH),
    (1430, "US Treasury Secretary Bessent: Iran sanctions could be on airline leasing companies.", BULLISH),
    (1431, "US Treasury Secretary Bessent on Iran: have had private discussions with China. We're discussing cooperation with China on Iran", NOSIGNAL),
    (1432, "US Treasury Secretary Bessent: Iran's protective shield had to be taken out.", BULLISH),
    (1441, "Iran's Galibaf: If the US siege is intensified, we will definitely respond militarily - Iranian media", BULLISH),
    (1450, "US Treasury Secretary Bessent: I expect everyone to come along with us on Iran.", BULLISH),
    (1471, "NATO Sec. Gen. Rutte: NATO stands in full solidarity with Germany after the Russian Hybrid Attack in Leipzig on the 14th August. NATO will continue to strengthen our ability to deter and defend all allies against any threat.", NOSIGNAL),
    (1472, "Russian Foreign Minister on the German accusations that Russia was behind attempted airport drone attack: Russia will respond to all anti-Russian actions - IFX.", NOSIGNAL),
    (1473, "US Official: US strikes Iranian targets in the Strait of Hormuz area in response to Iranian attacks on ships - N12 News' Ravid.", BULLISH),
    (1474, "US CENTCOM: The US military launched fresh strikes on Iranian targets.", BULLISH),
    (1475, "IAEA Report shows IAEA estimates of Iran's enriched uranium stocks up to June 13th, 2025, are unchanged from previous reports.", NOSIGNAL),
    (1476, "IAEA: The missing Iranian uranium is a proliferation concern.", BULLISH),
    (1477, "The US embassy in Israel warns American citizens in the Middle East of a possible escalation - Sky News Arabia.", BULLISH),
    (1478, "Four projectiles struck areas in southeastern Chabahar and Konarak; assessments of possible damage are underway - Iran's IRNA cites Provincial Security Official", BULLISH),
    (1479, "Russia's Putin, China's Xi, and US Trump may hold trilateral Talks at the APEC summit - Vesti", BEARISH),
    (1480, "Trump: US striking Iranian targets near the Strait of Hormuz. - Truth Social", BULLISH),
    (1481, "Trump: If Iran retaliates for this very justified attack, they will be hit again at a much harder and higher level - Truth Social", BULLISH),
    (1485, "Iran to deliver a greater response to US strikes - Tasnim", BULLISH),
    (1486, "Iran will respond to US attacks with a response 'several times larger and US bases and interests in the region will be targeted - Tasnim cites senior Iranian Military Source.", BULLISH),
    (1487, "Iran's IRGC: Severe punishment awaits the US - IRIB", BULLISH),
    (1488, "US oil tops $90 a barrel for the first time since late July.", BULLISH),
    (1489, "The US targeted a factory, pier, and port tower in southern Iran - Mehr", BULLISH),
    (1494, "Trump to Fox News: Agreement with Iran not worth the paper it's written on; gave Iran a lot of chances.", BULLISH),
    (1495, "Ukraine’s President Zelenskiy: Ready to pause drone strikes on Russia if allies ask.", BEARISH),
    (1496, "Ukraine’s President Zelenskiy: Ukraine to take into account future talks in Moscow.", BEARISH),
    (1497, "US targets Jiroft Airport in southeastern Iran - IRIB", BULLISH),
    (1498, "Iranian missiles and drones fired toward enemy positions - Fars", BULLISH),
    (1500, "Trump: New US strikes targeted Iran's radar system - Fox News", BULLISH),
    (1501, "NYMEX WTI crude October futures settle at $90.22 a barrel, up $4.46, 5.20%.", BULLISH),
    (1502, "NYMEX Gasoline October futures settle at $3.1351 a gallon.", NOSIGNAL),
    (1503, "NYMEX Diesel October futures settle at $4.6773 a gallon.", NOSIGNAL),
    (1504, "NYMEX Natural Gas October futures settle at $2.9040/MMBTU.", NOSIGNAL),
    (1508, "Russia: Germany's claim that Moscow was behind the attempted drone attack at Leipzig airport is baseless and absurd - Embassy", NOSIGNAL),
    (1509, "Brent crude futures settle at $94.65/bbl, up $4.16, 4.6%.", BULLISH),
    (1510, "Russia: Germany's Leipzig claim is a provocation that serves the interests of Ukraine, the militaristic wing of the European elite, and arms makers.", NOSIGNAL),
    (1511, "Iran: The US struck Kuhestak in southern Hormozgan - Fars", BULLISH),
    (1512, "Russia: Germany's sanctions over the Leipzig allegations are an unprecedented escalation and will not go unanswered.", NOSIGNAL),
    (1514, "New explosions heard in Iran's southeastern port of Chabahar - Mehr News Agency", BULLISH),
    (1515, "Iran's IRGC has begun retaliatory strikes against the US - IRIB", BULLISH),
    (1516, "IRGC: US attacks will tighten the lock on the Strait of Hormuz - Statement", BULLISH),
    (1519, "US missile attack targets site near Iran's Ahvaz - Mehr", BULLISH),
    (1523, "Tasnim News: Residents report air defences activated in eastern Tehran, no official confirmation.", BULLISH),
    (1534, "No US casualties from Iranian strike on facilities in Jordan so far, two US officials say - source", NOSIGNAL),
    (1536, "Iranian media: military launches large-scale drone strike on U.S. base in Bahrain; no official confirmation", BULLISH),
    (1538, "G20 concerned by ongoing disruptions to energy trade and safe navigation through Strait of Hormuz, G20 chair's statement:", BULLISH),
    (1548, "Kuwait air defences responding to hostile drone strikes after Iranian attack: Kuwaiti army", BULLISH),
    (1553, "Centcom: U.S. Central Command forces complete wave of strikes on Iranian military targets Sept. 1", BULLISH),
    (1582, "BoJ Governor Ueda: focus on Middle East conflict, oil demand, FX impact on economy and prices in policy guidance", NOSIGNAL),
    (1586, "Bahrain: air defense systems shot down Iranian drones over kingdom", BULLISH),
    (1587, "Russia's deputy foreign minister Grushko: no basis for Black Sea grain deal to restart", NOSIGNAL),
    (1589, "Russia's Grushko: Moscow to react to Bonn consulate shutdown", NOSIGNAL),
    (1593, "Russia attacks Ukraine's Odesa, damages infrastructure: Odesa official", BULLISH),
    (1602, "Iran’s Revolutionary Guards: combined missile and drone attacks on U.S. bases in Iraq’s Erbil; no official confirmation", BULLISH),
    (1613, "U.S. energy secretary says 17 million barrels of oil passed through Strait of Hormuz on Monday", BEARISH),
    (1614, "U.S. military attacked two Iranian government tankers: Axios", BULLISH),
    (1622, "Israeli military: sirens warn of hostile aircraft infiltration in Kfar Yuval", NOSIGNAL),
    (1651, "Four commodity vessels pass Strait of Hormuz on Tuesday, data shows, compared with 10-day average of around 13", BULLISH),
    (1685, "Russian finance minister Siluanov: grounds to expand financial ties with U.S. despite current complications - Interfax", NOSIGNAL),
    (1686, "Russia's Siluanov: dialogue with U.S. should continue - Interfax", BEARISH),
    (1694, "Bahrain Defence Force says air defences intercepted and destroyed multiple Iranian aerial attacks", BULLISH),
    (1695, "Japan oil refinery operating rate 82.6% in week to August 29.", NOSIGNAL),
    (1701, "Iran's IRGC: Attacked US assets in Kuwait, Bahrain, Jordan, and Iraq's Erbil", BULLISH),
    (1708, "Iran's IRGC: Some of US' overnight attacks came from Kuwait.", BULLISH),
    (1732, "Iran: US attacks killed 4 IRGC members in Kermanshah - Tasnim", NOSIGNAL),
    (1735, "Iran's Revolutionary Guards: two tankers struck naval mines, halted journey in Strait of Hormuz - statement", BULLISH),
    (1746, "Russia's Deputy PM Novak: Russian oil companies provided funds to safeguard refineries: TASS", NOSIGNAL),
    (1747, "Russia’s Deputy PM Novak: Russian oil companies coordinating with defense ministry on refineries, Tass", NOSIGNAL),
    (1765, "EU's Von Der Leyen: We will increase our pressure on Russia", BULLISH),
    (1770, "Saudi Arabia: Iran attacked Saudi Sidr vessel in the Strait of Hormuz - Foreign Ministry", BULLISH),
    (1780, "US Energy Secretary Wright: Betancourt company has been a competent operator in Venezuela, we think this increases confidence in law and contract security in Venezuela - CNBC", BEARISH),
    (1781, "US Energy Secretary Wright: I think we will be at well over 1.5 million barrels a day in Venezuela by the first half of next year", BEARISH),
    (1782, "US Treasury Secretary Bessent, on Iran and Russia: My message to everyone is to stay away - Fox News interview", BULLISH),
    (1783, "US Treasury Secretary Bessent on Iran, Russia: No one should support this regime.", BULLISH),
    (1784, "US Treasury Secretary Bessent, on Iran and sanctions: Going to systemically take out bad actors - Fox news interview", BULLISH),
    (1785, "US Treasury Secretary Bessent on Iran, sanctions: Airlines, maritime, digital assets could be targets.", BULLISH),
    (1786, "US Treasury Secretary Bessent: We are having fulsome talks with anyone supporting Iran", BULLISH),
    (1788, "US Treasury Secretary Bessent: Chevron CEO doing a fantastic job managing Venezuela assets", NOSIGNAL),
    (1789, "US Energy Secretary Wright: Over 17 mln barrels oil flowed through Strait of Hormuz on Monday.", BEARISH),
    (1803, "Fed's Williams: There is correlation between bond yields and Middle East conflict.", NOSIGNAL),
    (1808, "Fed's Williams: Tariffs and middle east war are big drivers of inflation over target.", NOSIGNAL),
    (1824, "Iran: US attacks hit telecoms, communication infrastructure.", NOSIGNAL),
    (1827, "US Energy Secretary Wright: Venezuela production is up 25%, exports up 50%.", BEARISH),
    (1828, "US Energy Secretary Wright: China won't have a claim to Venezuela's oil fields", NOSIGNAL),
    (1829, "US Energy Secretary Wright: I haven't had discussions with Venezuela on OPEC.", NOSIGNAL),
    (1830, "Canada government will extend the temporary pause of the federal fuel excise tax on gas and diesel until Jan 31, 2027 - CTV News", NOSIGNAL),
    (1831, "US Energy Secretary Wright: It is unlikely Venezuela oil will go into SPR.", NOSIGNAL),
    (1832, "US Energy Secretary Wright: Venezuela output will allow for swapping barrels", BEARISH),
    (1833, "Ukraine has hit 12 large Russian oil refineries in August - Ukrainian Defence Ministry.", BULLISH),
    (1834, "US Energy Secretary Wright: Trump is changing the importance of the Strait of Hormuz", NOSIGNAL),
    (1835, "US Energy Secretary Wright: The US Navy is ‘overwhelming Iranian attacks\"", BEARISH),
    (1836, "US Energy Secretary Wright: The US navy is getting oil to the market.", BEARISH),
    (1842, "BoC: The Middle East conflict and US tariffs situations remain fluid.", NOSIGNAL),
    (1847, "BoC's Gov. Macklem: Ongoing conflict in the Middle East is keeping energy prices higher for longer and is increasing the upside risks to the outlook for inflation.", BULLISH),
    (1849, "Russia’s Deputy PM Novak: Russia is importing gasoline, diesel, and jet fuel - Tass.", BULLISH),
    (1855, "Chevron sees billions of barrels of Venezuela's oil resources. $CVX", BEARISH),
    (1859, "Iran Border Guards seize a vessel with 382,000 litres of smuggled fuel in the northern gulf, and detain 11 foreign suspects - Iranian State Media.", BULLISH),
    (1860, "The OPEC+ meeting on Sunday will not make any oil output policy decision, and will focus on discussing the market - Three Sources.", NOSIGNAL),
    (1861, "Chevron: Strait of Hormuz flows help buy time for oil supply. $CVX", BEARISH),
    (1862, "Russia’s Deputy PM Novak: Talk of OPEC+ quota cuts is not happening right now, there is a shortage in the market - IFX.", BULLISH),
    (1863, "Russia’s Deputy PM Novak: We are seeing a recovery in oil demand - IFX.", BULLISH),
    (1864, "Russia’s Deputy PM Novak: OPEC+ ministers will discuss the market situation and compliance with the agreement at their meeting on Sunday - IFX.", NOSIGNAL),
    (1867, "US Secretary of State Rubio: The US is now negotiating a license with Ukraine on Patriots.", NOSIGNAL),
    (1876, "BoC's Gov. Macklem: Inflation is very concentrated in gasoline and oil prices. There is no clear end to it in sight.", BULLISH),
    (1889, "Trump: Now that we have the Strait under US control, should we change the name of the Hormuz Strait to the Trump Strait??? - Truth Social.", NOSIGNAL),
    (1893, "Chevron and the Venezuelan government sign an oil deal, a bonus venture deal in the Orinoco Belt. $CVX", BEARISH),
    (1900, "White House: The barrels from the Venezuela deal could hit reserves in the US in November.", BEARISH),
    (1918, "Trump on Iran: Regime getting weaker by the day.", NOSIGNAL),
    (1922, "Trump: Oil prices will come down.", BEARISH),
    (1923, "Trump on Iran: Renewed campaign against Iran won't continue for too long.", BEARISH),
    (1924, "Trump: controlling the Hormuz Strait.", BEARISH),
    (1925, "Trump on Iran: Iran was trying to rebuild radar and missile systems; we took it out.", BULLISH),
    (1926, "Trump: Prepared to do another attack on Iran.", BULLISH),
    (1927, "Trump on Iran war: Don't think it'll be much longer.", BEARISH),
    (1928, "Trump: brought up price gouging to oil execs yesterday.", NOSIGNAL),
    (1929, "Trump: Want retail gasoline prices to come down.", NOSIGNAL),
    (1930, "Trump on Russia's war in Ukraine: They have to stop that war.", BEARISH),
    (1932, "NYMEX WTI crude October futures settle at $91.01 a barrel, up 79 cents, 0.88%.", BULLISH),
    (1933, "NYMEX Gasoline October futures settle at $3.1038 a gallon.", NOSIGNAL),
    (1934, "NYMEX Diesel October futures settle at $4.6822 a gallon.", NOSIGNAL),
    (1935, "NYMEX Natural Gas October futures settle at $2.9560/MMBTU.", NOSIGNAL),
    (1937, "Brent crude futures settle at $95.63/bbl, up 98 cents, 1.04%.", BULLISH),
    (1945, "RBNZ Governor Breman: Expect to see indirect impact of higher oil prices coming through in the coming quarters.", NOSIGNAL),
    (1969, "Russian air strike damages multi-story residential building in Ukraine's Odesa, official says", NOSIGNAL),
    (1985, "China vice premier Ding Xuexiang meets Russia’s Putin in Vladivostok: Xinhua", NOSIGNAL),
    (1986, "China vice premier Ding Xuexiang: prospects for expanding China-Russia Far East development ties are broad and promising - Xinhua", NOSIGNAL),
    (1987, "China Vice Premier Ding Xuexiang: Leadership of two heads of state crucial to unshakable China-Russia ties amid turbulent global climate - Xinhua", NOSIGNAL),
    (1999, "Kuwait air defences responding to missile, drone strikes: Kuwaiti army", BULLISH),
    (2000, "Kuwait army: attacks part of Iranian hostility", BULLISH),
    (2003, "Russia to shut Goethe-Institut branches after German drone accusations: Foreign Minister Lavrov", NOSIGNAL),
    (2010, "Six commodity ships pass Strait of Hormuz on Wednesday, below 10-day average of about 13, data shows", BULLISH),
    (2011, "Saudi Arabia S&P Global August composite PMI at 53.8 vs 53.1 in July", NOSIGNAL),
    (2016, "UAE President and Trump discuss Middle East developments and bilateral cooperation in phone call - UAE State News Agency", NOSIGNAL),
    (2014, "Russia’s Deputy PM Novak: Russia to slightly cut oil output in 2026 - Tass", BULLISH),
    (2020, "Russia’s Deputy PM Novak: Russia's oil output drop this year is temporary - Tass", BEARISH),
    (2026, "Russian defence ministry: Russian forces hit two Ukrainian cargo vessels in black sea - IFX", BULLISH),
    (2028, "US average diesel price gains to highest since 2022 - AAA data", BULLISH),
    (2038, "Putin: Russia and Ukraine must first agree between each other", NOSIGNAL),
    (2049, "Ukraine's PM: Energy infrastructure damaged in Russian overnight attack", BULLISH),
    (2058, "Russian state's budget proceeds from oil and gas sales at 424 bln roubles in August, from 934 bln roubles in July - Finance ministry", NOSIGNAL),
    (2062, "Israel's Defence Minister Katz: Iran could resort to desperate measures due to pressure", BULLISH),
    (2063, "Israel's Defence Minister Katz: Iran attack on Israel would free us from existing limits", BULLISH),
    (2064, "Israel's Defence Minister Katz warns Israel would “return Iran to the Stone Age\" if attacked", BULLISH),
    (2066, "Russia’s Deputy PM Novak: Russian market fully supplied with diesel and jet fuel", BEARISH),
    (2083, "UK PM Burnham's Spokesperson: Britain has summoned Russian charge d'affaires over Leipzig airport attack", NOSIGNAL),
    (2084, "Russia's ambassador to Norway on Norway seizing Russian ship: Russia will appeal the court's decision - TASS.", NOSIGNAL),
    (2087, "Three Iranian army pilots were killed in US strikes earlier this week - Tasnim", NOSIGNAL),
    (2088, "Ukraine's Navy: Hit Russian support vessel in the port of Sochi", BULLISH),
    (2185, "China to deepen investment cooperation with Russia - Xinhua", NOSIGNAL),
    (2196, "Trump administration ratchets up its fight to get more oil flowing from California - AP news", BEARISH),
    (2201, "Russia summons Norwegian ambassador over seizure of Russian ship by Norway. Russia lodges protest to ambassador - RIA", NOSIGNAL),
    (2205, "Yemeni media: Escalation of clashes between Yemeni armed forces and Saudi mercenaries on Taiz front, with reports of many mercenaries fleeing, killed or injured - Mehr News", NOSIGNAL),
    (2222, "BoE's Pill: Iran war has not de-anchored long-term expectations.", NOSIGNAL),
    (2227, "Saudi Arabia sets October Arab Light Crude Oil OSP to Asia at minus $2/bbl vs Oman/Dubai average - pricing document.", NOSIGNAL),
    (2234, "Saudi Arabia sets October Arab Light Crude oil OSP to NW Europe at minus $2.15/bbl vs ICE Brent settlement - pricing document.", NOSIGNAL),
    (2235, "Saudi Arabia sets October Arab light crude oil OSP to US at plus $4.60/bbl vs ASCI - pricing document.", NOSIGNAL),
    (2236, "Israel's Prime Minister Netanyahu: I am convinced of our ability to eliminate this threat once and for all, meaning, to topple the regime in Iran - Israel's Hayom News", BULLISH),
    (2237, "Israel's Prime Minister Netanyahu on toppling Iran: Central mission that still lies ahead of us, but it is close. It is not impossible. It is within our reach.", BULLISH),
    (2239, "Oman quietly rejects Iran’s pitch for Strait of Hormuz fees — despite IRGC claim of deal - NY Post", NOSIGNAL),
    (2243, "Iran's Minister of Oil: A significant portion of the damage to energy facilities during the two recent wars has been repaired.", BEARISH),
    (2245, "Iran's attacks didn't impact facilities with US forces - CBS", BEARISH),
    (2246, "US VP Vance: US taxpayers to also win with Venezuela oil deal.", BEARISH),
    (2250, "US VP Vance on Gasoline prices: They're high because Iran is shooting at ships.", BULLISH),
    (2251, "US Vice President Vance: About 15 million barrels out of the Strait of Hormuz yesterday.", NOSIGNAL),
    (2252, "US VP Vance: I won't make promises on the timing of lower gasoline prices.", NOSIGNAL),
    (2257, "US VP Vance reiterates that the US has a set of tools to use against Iran.", BULLISH),
    (2259, "US VP Vance: We're not talking to Iran unless they stop shooting at ships.", BULLISH),
    (2261, "US VP Vance: Would not call it a war in Iran.", BEARISH),
    (2262, "US VP Vance: Won't set an artificial timeline for the end of the war in Iran.", NOSIGNAL),
    (2264, "Trump: 30 to 40 boats nightly coming through Hormuz Strait.", BEARISH),
    (2266, "Trump: I did the right thing on Iran.", NOSIGNAL),
    (2267, "Trump: I just want the war ended in Ukraine", BEARISH),
    (2268, "US VP Vance on Iran attempted cyberattack: Confident homeland is safe.", NOSIGNAL),
    (2270, "NYMEX WTI Crude October futures settle at $91.30 a barrel,  up 29 cents, 0.32%.", BULLISH),
    (2271, "NYMEX Diesel October futures settle at $4.5936 a gallon.", NOSIGNAL),
    (2272, "NYMEX Gasoline October futures settle at $3.1349 a gallon.", NOSIGNAL),
    (2273, "Nymex Natural Gas October futures settle at $2.9130/MMBTU.", NOSIGNAL),
    (2274, "Iraq's August oil exports 73m bbl, highest in the Iran war - SOMO", BEARISH),
    (2275, "Iraq's oil revenues in August stood at around $4.5b - SOMO", NOSIGNAL),
    (2277, "US VP Vance: China is willing to be more responsible regarding Iran.", NOSIGNAL),
    (2282, "Brent crude futures settle at $95.52/bbl, down 11 cents, 0.12%.", BEARISH),
    (2283, "Iraq's losses since the Iran war are nearly $80b - SOMO", NOSIGNAL),
    (2287, "Iran's Minister of Oil: We have started drilling more than 30 wells in the South Pars gas field, and some of them have yielded positive results.", BEARISH),
    (2289, "Patrick De Haan of GasBuddy on X: US average diesel prices hit a new record of $5.820/gallon", BULLISH),
    (2294, "Iran's Foreign Ministry Spokesperson Baghaei: Iran's defensive strikes have been exclusively against military targets.", BEARISH),
    (2321, "Argentina president: to sign decree sanctioning companies exploring oil off Falkland Islands", BULLISH),
    (2323, "Argentina president: to submit bill to congress to tighten sanctions on companies involved in unauthorized activities", NOSIGNAL),
    (2335, "South Korea Blue House: Practical contribution options for Strait of Hormuz under review include military measures", BULLISH),
    (2336, "South Korea Blue House: claims about no help on Hormuz are false", NOSIGNAL),
    (2352, "Russia’s Deputy PM Novak: effort ongoing to finalize power of Siberia 2 gas pipeline deal with China - TASS", NOSIGNAL),
    (2361, "Iraq's Somo requests September-December gasoil delivery, document shows; second purchase tender this year", NOSIGNAL),
    (2362, "Four commodity ships pass Strait of Hormuz on Thursday, below 10-day average of about 15, data shows", BULLISH),
    (2365, "Russia's Sechin: China has overcome the Hormuz crisis thanks to settings up of reserves and cooperation with Russia", BEARISH),
    (2368, "Russia's Novak: China will account for more than 60% of Russia's total natural gas exports by 2030", NOSIGNAL),
    (2369, "Russia attacked energy infrastructure facilities in Ukraine's Odesa region overnight - Ukraine's energy ministry", BULLISH),
    (2371, "China's Xi calls for deeper China-Russia energy cooperation - CCTV", NOSIGNAL),
    (2382, "US Envoy Witkoff and Kushner to visit Russia and Ukraine on September 5-6 - TASS cites source", BEARISH),
    (2383, "US Envoy Witkoff and Kushner to visit first Moscow, then Kyiv - Tass", BEARISH),
    (2385, "Oil production in Kazakhstan for 2027 is planned at 96 million tonnes - IFX cites budget project", NOSIGNAL),
    (2388, "Discussions on US negotiators coming to Ukraine are ongoing, teams spoke about September 6th - Sources", BEARISH),
    (2394, "Iran Army: Targeting Israel is 'far easier' than before - TV", BULLISH),
    (2415, "Ukraine expects new dynamics from talks with the US on peace efforts", BEARISH),
    (2416, "Ukraine sees growing ‘appetite’ among European allies to renew serious talks on frozen Russian assets - Senior government official", NOSIGNAL),
    (2417, "Ukraine refutes concerns of some EU allies that frozen russian assets are leverage in peace talks - Senior government official", NOSIGNAL),
    (2440, "Trump envoys Witkoff and Kushner to travel to Moscow and Kyiv this weekend - Axios", BEARISH),
    (2441, "Iran's Military Spokesperson: We will conduct preemptive operations wherever we feel threatened.", BULLISH),
    (2443, "Iran's Army Spokesman: Response to any potential Israeli aggression will be faster and more devastating.", BULLISH),
]
