"""Hand-read labels for the first 79 narrative headlines from the live feed.

This is the eval set. It is the only way to tell whether a lexicon change
improved the filter or merely moved the errors around, so it is checked in and
should grow as the corpus grows.

Labels are a human reading of whether the headline could plausibly move crude.
"""

from cns.relevance import GEO_RISK, IRRELEVANT, OIL_DIRECT

LABELLED: list[tuple[str, str]] = [
    ("Iran and Oman aim for a permanent Hormuz route in 60 days - Tasnim", GEO_RISK),
    ("Iranian Deputy Foreign Minister Gharibabadi: Iran told negotiators that the US must correct its errors and return to its commitments if it wants a reopening of the Strait of Hormuz -  State TV", GEO_RISK),
    ("Fed's Barkin: If debt rises at some point, investors will stop buying.", IRRELEVANT),
    ("Rubio tells foreign counterparts u.s. unlikely to launch new Iran strikes for time being: Axios", GEO_RISK),
    ("Ukraine's Zelenskiy on X: We expect more cooperation and China's key diplomatic role in ending Russia's war against our country", GEO_RISK),
    ("Ukraine's Zelenskiy on X: peace could be a common accomplishment", GEO_RISK),
    ("Poll: BoJ to raise rates to minimum 1.50% in Q1 2027, narrow majority of economists forecast (up from 1.25% in prior survey)", IRRELEVANT),
    ("Poll: Japan PM Takaichi's fiscal policies exert downward pressure on yen, 89% of economists say", IRRELEVANT),
    ("Poll: 69% of economists say July's Japan-U.S. coordinated FX intervention wasn't very effective or not effective at all", IRRELEVANT),
    ("Poll: Bank of Japan to lift benchmark interest rate to 1.25% in September, say 57% of economists (up from 5% in prior survey)", IRRELEVANT),
    ("Trump administration sends agreement on civil nuclear energy with Saudi Arabia to Congress: US administration official", GEO_RISK),
    ("Trump says nuclear deal with Saudi Arabia will advance only if Riyadh joins Abraham Accords, recognizes Israel: US official", GEO_RISK),
    ("China PBOC seen setting yuan midpoint at 6.7166 per dollar: estimate", IRRELEVANT),
    ("Darline Graham wins South Carolina Republican primary runoff for U.S. Senate: DDHQ projects", IRRELEVANT),
    ("BOJ: governor Ueda will skip this week's Jackson Hole meeting", IRRELEVANT),
    ("Darline Graham wins South Carolina Republican primary runoff for US Senate: NBC News projects", IRRELEVANT),
    ("BOJ: Board member Tamura to attend on Ueda's behalf, no media access", IRRELEVANT),
    ("China sets yuan midpoint 663 pips below estimate, biggest weak-side deviation since Feb. 27, 2026", IRRELEVANT),
    ("China c.bank injects 239.5 bln yuan via 7-day reverse repos at 1.40%: statement", IRRELEVANT),
    ("Meta: states have discussed resolving teen social media harm lawsuit", IRRELEVANT),
    ("Australia July RBA trimmed mean CPI rises 3.6% year-on-year", IRRELEVANT),
    ("Australia July RBA weighted median CPI rises 0.4% month/month", IRRELEVANT),
    ("Australia July RBA weighted median CPI at 3.6% year/year", IRRELEVANT),
    ("Australia July CPI (all groups) rises 3.5% year/year", IRRELEVANT),
    ("Australia Q2 construction output falls 2.1% q/q, seasonally adjusted (Poll: +0.5%)", IRRELEVANT),
    ("Australia July RBA trimmed mean CPI rises 0.5% month on month", IRRELEVANT),
    ("Australia July CPI (all groups) rises 1% m/m", IRRELEVANT),
    ("Taiwan overnight interbank rate starts at 0.805% compared with previous session at 0.805%", IRRELEVANT),
    ("China's onshore yuan strengthens to 6.7051 per dollar, highest since Feb. 2, 2023", IRRELEVANT),
    ("Microsoft 365: Maintenance activity causes degraded Microsoft Teams functionality for users in Asia-Pacific", IRRELEVANT),
    ("Microsoft 365 halts maintenance activity: service returns to normal availability levels", IRRELEVANT),
    ("Russia, Ukraine discuss prisoner of war exchange: Tass", GEO_RISK),
    ("Wildberries warehouse in Russia's Tambov region ablaze after drone strike: local governor", GEO_RISK),
    ("Asian Development Bank: issues 20 billion yen bonds to fund water infrastructure projects", IRRELEVANT),
    ("Microsoft 365 confirms issue affecting Microsoft Teams service in Asia-Pacific region resolved", IRRELEVANT),
    ("China finance ministry offers 3-month bills with 1.0899% yield: traders", IRRELEVANT),
    ("Japan econ minister Kiuchi: expects consumer prices to gradually increase amid Middle East situation", GEO_RISK),
    ("Five commodity ships pass Strait of Hormuz on Tuesday, well below 10-day average of 15, data shows", GEO_RISK),
    ("Retired teacher Dan J. Sullivan to move on to general election for US Senate in Alaska: NBC projects", IRRELEVANT),
    ("Russia downs 426 drones overnight: Russian news agencies cite defence ministry", GEO_RISK),
    ("SoftBank considers bond sale up to $20 billion for OpenAI funding", IRRELEVANT),
    ("ECB's Schnabel: The ECB must prevent second-round effects early on.", IRRELEVANT),
    ("ECB's Schnabel: Market seems to understand ECB reaction function well.", IRRELEVANT),
    ("ECB's Schnabel: Extent of tightening to depend on incoming data.", IRRELEVANT),
    ("ECB's Schnabel: Natural gas situation particularly concerning.", OIL_DIRECT),
    ("ECB's Schnabel: Economy looks to be gaining further momentum.", IRRELEVANT),
    ("ECB's Schnabel: Inflation likely to top 2% for extended period.", IRRELEVANT),
    ("ANZ bank now sees RBA raising the cash rate by 25bps in November", IRRELEVANT),
    ("Deepseek rev as of July roughly tenfold of FY25 rev - The Information", IRRELEVANT),
    ("Japan plans to diversify oil procurement - Cabinet Office", OIL_DIRECT),
    ("Japan to support construction of pipelines on non-Hormuz routes.", OIL_DIRECT),
    ("Japan aims to provide support with extra shipping costs.", IRRELEVANT),
    ("Tankers load 4 mln bbls of Saudi Crude in ship-to-ship transfer off Oman, cargoes heading for China - Shipping Data.", OIL_DIRECT),
    ("Saudi Aramco offers Arab medium, heavy crude oil for September loading to Asian refiners - Sources", OIL_DIRECT),
    ("ICC's Akane: Expect Japan government to boost aid to reduce impact of U.S. sanctions", GEO_RISK),
    ("Fitch Ratings: China deflation eases but weak domestic demand could weigh on prices.", IRRELEVANT),
    ("Iran: Qatar has told Tehran it is unaware of the fate of Iranian pilots, urge Doha to step up efforts to determine their fate - Tasnim", GEO_RISK),
    ("Canada's PM Carney set to address the EU Parliament in mid-September, expected to attend Von der Leyen's Strasbourg speech", IRRELEVANT),
    ("German Finance Minister: Based on the special budget, we will increase investment in research and development by 60% in 2027 from 2026", IRRELEVANT),
    ("German Finance Minister: After one year, 50 billion EUR of the 500 billion EUR special budget has already been allocated", IRRELEVANT),
    ("German Finance Minister: In the next cabinet meeting, I will be presenting the income tax reform.", IRRELEVANT),
    ("Germany's Chancellor Merz: German industry has changed its stance on trade imbalances", IRRELEVANT),
    ("Germany's Chancellor Merz has asked the cabinet to work on proposals for EU trade with China.", IRRELEVANT),
    ("German finance minister: The turmoil we are seeing in the bond markets is related to the war in Iran", GEO_RISK),
    ("Germany's Merz: We have absolutely no difficulty refinancing on the capital markets, and I don't see any coming either", IRRELEVANT),
    ("Germany's Chancellor Merz: Expect no change to Germany's top credit rating", IRRELEVANT),
    ("Germany's Chancellor Merz: All incentives for early retirement must be avoided", IRRELEVANT),
    ("Iran, Oman agreed on share of Hormuz revenues - IRGC", GEO_RISK),
    ("Iran's revolutionary guards spokesperson: Agreements have been made on the share of Iran and Oman in the waters of the Strait of Hormuz", GEO_RISK),
    ("Iran's Revolutionary Guards Spokesperson: Agreements include the share of Iran and Oman in the Strait's revenues - Tasnim", GEO_RISK),
    ("Iran's revolutionary guards spokesperson: The US is obstructing the negotiation process between Oman and Iran, which has delayed matters", GEO_RISK),
    ("Iran's Revolutionary Guards spokesperson: The strait will not be opened if the US does not accept our conditions.", GEO_RISK),
    ("Secured overnight financing rate: 3.66% August 25th vs 3.65% August 24th", IRRELEVANT),
    ("US short-term interest-rate futures slightly trim earlier gains after economic data", IRRELEVANT),
    ("Alibaba releases a smaller, cost-effective Qwen AI model $BABA", IRRELEVANT),
    ("Ukraine's President Zelenskiy: Ukraine is now in contacts with the US, discussing ways to achieve peace", GEO_RISK),
    ("Senior Iranian Source: An agreement with Oman over the Strait of Hormuz has not yet been finalised.", GEO_RISK),
    ("Iran and Oman are still working on the details of an agreement over the Strait of Hormuz - Senior Iranian Source.", GEO_RISK),
    ("Effective Fed Funds Rate 3.63% August 25 vs 3.63% August 24.", IRRELEVANT),
    ("Lebanon's President Aoun continues to advocate for US-brokered negotiations with Israel - Fars News", GEO_RISK),
]
